src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: false)]
    private ?string $illustration = null; //image main

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $illustrationun = null; //image deux

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $illustrationdeux = null; //image trois

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $illustrationtrois = null; //image quatre

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $illustrationquatre = null; //image cinq

    #[ORM\Column(length: 100)]
    private ?string $subtitle = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $codeRga = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $caracteristique = "-";    
    
    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?float $pricepromo = null;

    #[ORM\Column(nullable: true)]
    private ?float $priceFDO = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?SubCategory $subCategory = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(name: "marque_id", referencedColumnName: "id", nullable: false)]
    private ?Marque $marque = null;

    #[ORM\Column(nullable: false)]
    private ?int $quantite = 0;

    #[ORM\Column(nullable: true)]
    private ?bool $isAffiche = null;

    #[ORM\Column]
    private ?bool $isBest = false;

    #[ORM\Column(nullable: true)]
    private ?bool $isDegressif = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isOccassion = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isSuisse = null;

    #[ORM\Column(nullable: true)]
    private ?string $accessoireLieA = null;
    
    #[ORM\Column(nullable: true)]
    private ?float $masse = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isVenteFlash = false;
    
    #[ORM\Column(nullable: true)]
    private ?bool $isForcesOrdre = null;
    
    #[ORM\ManyToOne(inversedBy: 'produit')]
    #[ORM\JoinColumn(nullable: true)]
    private ?MainPortee $mainportee = null;

    #[ORM\OneToMany(mappedBy: 'pid', targetEntity: OrderDetails::class)]
    private Collection $orderDetails;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: MailRetourStock::class)]
    private Collection $produitMailStockIn;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Famille $famille = null;

    #[ORM\ManyToOne(inversedBy: 'produit')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Calibre $calibres = null;

    #[ORM\OneToMany(mappedBy: 'pid', targetEntity: VenteFlash::class)]
    private Collection $produitsFlash;

    #[ORM\OneToMany(mappedBy: 'pid', targetEntity: BourseArmes::class)]
    private Collection $bourseArmes;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Fournisseurs $fournisseurs = null;

    #[ORM\Column(nullable: true)]
    private ?int $munitionNbBoite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $referenceAssociation = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isCarteCadeau = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Taille $taille = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
        $this->produitMailStockIn = new ArrayCollection();
        $this->produitsFlash = new ArrayCollection();
        $this->bourseArmes = new ArrayCollection();
    }

    public function __toString() //recherche par nom pour le search et searchtype
    {
       return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(?string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getIllustrationUn(): ?string
    {
        return $this->illustrationun;
    }

    public function setIllustrationUn(?string $illustrationun): self
    {
        $this->illustrationun = $illustrationun;

        return $this;
    }

    public function getIllustrationDeux(): ?string
    {
        return $this->illustrationdeux;
    }

    public function setIllustrationDeux(?string $illustrationdeux): self
    {
        $this->illustrationdeux = $illustrationdeux;

        return $this;
    }

    public function getIllustrationTrois(): ?string
    {
        return $this->illustrationtrois;
    }

    public function setIllustrationTrois(?string $illustrationtrois): self
    {
        $this->illustrationtrois = $illustrationtrois;

        return $this;
    }

    
    public function getIllustrationQuatre(): ?string
    {
        return $this->illustrationquatre;
    }

    public function setIllustrationQuatre(?string $illustrationquatre): self
    {
        $this->illustrationquatre = $illustrationquatre;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCodeRga(): ?string
    {
        return $this->codeRga;
    }

    public function setCodeRga(?string $codeRga): self
    {
        $this->codeRga = $codeRga;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCaracteristique(): ?string
    {
        return $this->caracteristique;
    }

    public function setCaracteristique(string $caracteristique): self
    {
        $this->caracteristique = $caracteristique;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPricePromo(): ?float
    {
        return $this->pricepromo;
    }

    public function setPricePromo(?float $pricepromo): self
    {
        $this->pricepromo = $pricepromo;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getIsAffiche(): ?bool
    {
        return $this->isAffiche;
    }

    public function setIsAffiche(bool $isAffiche): self
    {
        $this->isAffiche = $isAffiche;

        return $this;
    }

    public function isIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }

    public function getIsDegressif(): ?bool
    {
        return $this->isDegressif;
    }

    public function setIsDegressif(bool $isDegressif): self
    {
        $this->isDegressif = $isDegressif;

        return $this;
    }

    public function getDegressifValues(){ //tableau défini les valeurs par boites des produits MUNITION EN DEGRESSIF
        return [1, 10, 20, 40, 100, 500, 1000];
    }

    public function getIsOccassion(): ?bool
    {
        return $this->isOccassion;
    }

    public function setIsOccassion(bool $isOccassion): self
    {
        $this->isOccassion = $isOccassion;

        return $this;
    }
    public function isSuisse(): ?bool
    {
        return $this->isSuisse;

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Entity\BourseArmes;
use App\Entity\ComptesDocuments;
use App\Entity\Produit;
use App\Entity\ProfessionnelAssociationCompte;
use App\Entity\VenteFlash;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Spipu\Html2Pdf\Tag\Html\Del;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Classe\CheckImage;
class CartController extends AbstractController
{
    private $entityManager;
    public function __construct(EntityManagerInterface  $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/mon-panier', name:'cart')]
    public function index(Cart $cart, RequestStack $stack): Response
    {
        // dd($cart->get());
        $dateNow = new DateTimeImmutable('now +1 hours');
        $siVenteFlash = $this->entityManager->getRepository(VenteFlash::class)->findAll();
        $documentClientCheck = $this->entityManager->getRepository(ComptesDocuments::class)->findOneByUser($this->getUser());
        $siProPolice = $this->entityManager->getRepository(ProfessionnelAssociationCompte::class)->findOneByUser($this->getUser());
        $venteFlashPrix = 0;
        $cartComplete = [];
        $enleverNonAffiche = [];

        if ($cart->get()) {
            foreach ($cart->get() as $id => $quantity) {
                $bourseArmes = $this->entityManager->getRepository(BourseArmes::class)->findOneBy(['pid' => $id]);
                $venteFlashPrix = $this->entityManager->getRepository(VenteFlash::class)->findOneBy(['pid' => $id]);
                if($venteFlashPrix !== null && $venteFlashPrix->getTemps() > $dateNow){
                    $cartComplete[] = [
                        'produit' => $this->entityManager->getRepository(Produit::class)->findOneById($id),
                        'quantity' => $quantity,
                        'priceVenteFlash' =>  $venteFlashPrix->getNewPrice(),
                        'dateVenteFlash' => $venteFlashPrix->getTemps(),
                        'bourseArme' => false,
                    ];

                } else if ($bourseArmes !== null && $bourseArmes->getDateLimite() > $dateNow) {
                    $cartComplete[] = [
                        'produit' => $this->entityManager->getRepository(Produit::class)->findOneById($id),
                        'quantity' => $quantity,
                        'priceVenteFlash' =>  0,
                        'bourseArme' => $bourseArmes->isAffiche()
                    ];
                } else {
                    $cartComplete[] = [
                        'produit' => $this->entityManager->getRepository(Produit::class)->findOneById($id),
                        'quantity' => $quantity,
                        'priceVenteFlash' => 0,
                        'bourseArme' => false,
                    ];
                }
            }
            foreach($cartComplete as $key => $lesproduits){ //verif s'il y a des produits qui sont devenus indisponibles
                if($lesproduits['produit'] == null){ //si n'existe PLUS (car effacé dans la BDD ?)
                    // dd($cartComplete[$key]);
                    unset($cartComplete[$key]);
                } else { //si existe
                    if($lesproduits['produit']->getIsAffiche() === false){ //si pas affiche alors INDISPONIBLE
                        $enleverNonAffiche[] = $lesproduits; //on garde le produit pour le tableau des indisponible
                        unset($cartComplete[$key]); //on le vide du tableau cart
                    }
                }
                
            }

            // dd($cartComplete);
            // dd($enleverNonAffiche);
            $checkImage = new CheckImage();
            $checkImage->verifSiImage($cartComplete);
            $checkImage->verifSiImage($enleverNonAffiche);

        }
        // dd($cartComplete);
        // if(count($cart->getFull()) == count($panier_article_quantite_verif)){
        //     $panier_article_precommande_uniquement = true;
        // } 
        return $this->render('cart/index.html.twig', [

            'cart'=>$cartComplete,
            'indisponible' => $enleverNonAffiche,
            'date' => $dateNow,
            'siProPolice' => $siProPolice,
            'documentClient' => $documentClientCheck,
        ]);

    }


    #[Route('/cart/add/{id}', name: 'add_to_cart')]
    public function add(Cart $cart, $id): Response
    {
        #dd($id); 
        $cart->add($id);


        return $this->redirectToRoute('cart');
    }

    #[Route('/nos-produits/cart/add', name: 'add_to_cart_from_panier')]
    public function addFromProduitPage(Request $req, Cart $cart)
    {
        $id = $req->request->get("id");
        // $produit = $this->entityManager->getRepository(Produit::class)->findOneBy(['id'=> $id]);
        $cart->add($id);
        return new Response();
    }

    #[Route('/cart/add/{id}/{quantite}', name: 'add_to_cart_cart')]
    public function addFromBoursePage(Request $req, Cart $cart, $id, $quantite) : Response
    {
        $quantitePrise = $quantite;
        $produit = $this->entityManager->getRepository(Produit::class)->findOneById($id);

        //$cart->add($id);
        
        if($quantitePrise > 0){ //pas de quantite negative
    
            $cart->addToPanier($id, $quantitePrise);
        }
        
        return $this->redirectToRoute('cart');  
    }

    #[Route('/produit-en-bourse/cart/add/{id}/quantite={quantite}', name: 'add_to_cart_bourse')]
    public function addCartInput(Request $req, Cart $cart, $id, $quantite) : Response
    {
        $quantitePrise = $quantite;
        $produit = $this->entityManager->getRepository(Produit::class)->findOneById($id);
        $quantiteCheck = $this->entityManager->getRepository(BourseArmes::class)->findOneByPid($produit)->getQuantiteMax();

        if($quantitePrise >= $quantiteCheck){ //si quantite prise égale ou supérieur à la quantité minimale autorisée
            $cart->addToPanierBourse($id, $quantitePrise);
            return $this->redirectToRoute('cart');
        } else { //sinon
            $this->addFlash('warning',"Vous n'avez pas sélectionné assez de quantité à commander.");
            return $this->redirectToRoute('app_produit_bourse', ['slug' => $produit->getSlug()]);        
        }
    }

    #[Route('/cart/remove', name: 'remove_my_cart')]
    public function remove(Cart $cart): Response
    {

        #dd($id);
        $cart->remove();

        return $this->redirectToRoute('app_products');
    }

    #[Route('/cart/delete/{id}', name: 'delete_to_cart')]
    public function delete(Cart $cart, $id): Response
    {

        #dd($id);
        $cart->delete($id);

      return $this->redirectToRoute('cart');
    }

    #[Route('/cart/decrease/{id}', name: 'decrease_to_cart')]
    public function decrease(Cart $cart, $id): Response
    {
        #dd($id);
        $cart->decrease($id);
        return $this->redirectToRoute('cart');
    }

    public function iconePanierQuantiteShow(Cart $cart, Request $req){ //pour l'icone du panier du header, pour afficher le nombre de produits dans le panier
        $count = 0;
        if($cart->get() !== null){
            foreach($cart->get() as $counting){ //à chaque itineration on compte combien de produit a cart
                $count = $count + $counting;
            }
        }
        // dd($count);
        return $this->render('cart/icone_cart.html.twig', [
            'quantite' => $count
        ]);
    }
}

templates/cart/icone_cart.html.twig
<b id="cart_quantite">{{ quantite }}</b>

templates/cart/index.html.twig
    {% extends 'base.html.twig' %}

    {% block title %}<title>Mon panier | Arsenal Pro</title>{% endblock %}
    {% block annonce %} {% endblock %}
    {% block content %}

        {{ render(controller('App\\Controller\\HomeController::banniereShow',{ 'titre' : "Mon panier", 'section' : 2, 'multi' : true })) }}
           <p>Retrouvez l'ensemble des produits que vous avez ajouté à votre panier</p>
        {% if cart|length > 0 %}
        <table class="table table_cart">
            <tbody>
            {% set total = null %}
            {% set siFDO = false %}
            {% for produit in cart %}
                {% set affichePrix = true %}
                {% if produit.priceVenteFlash > 0 and produit.produit.isVenteFlash and (produit.dateVenteFlash|date('Y-m-d H:i:s') > date|date('Y-m-d H:i:s') ) %} {# si produit en vente flash #}
                    {% set produitprix = produit.priceVenteFlash %}
                {% elseif produit.produit.pricepromo and produit.produit.pricepromo != produit.produit.price and produit.produit.pricepromo < produit.produit.price %}
                    {% set produitprix = produit.produit.pricepromo %}
                {% else %}
                    {% set produitprix = produit.produit.price %}
                {% endif %}

                {% if produit.produit.isForcesOrdre %} {# si produit classé en forces de l'ordre #}
                    {% if siProPolice %}
                        {% if siProPolice.numeroMatricule == null %} {# prix à 0 si non police #}
                            {% set produitprix = 0 %}
                            {% set affichePrix = false %}
                        {% else %}
                            {% set produitprix = produit.produit.price %}
                        {% endif %}
                    {% else %}
                        {% set produitprix = 0 %} {# prix à 0 si non police #}
                        {% set affichePrix = false %}
                    {% endif %}
                {% endif %}

                {% if produit.produit.priceFDO and produit.produit.priceFDO > 1 %} {# si prix special FDO appliqué pour un produit (non FDO ou oui FDO) #}
                    {% if siProPolice %}
                        {% if siProPolice.numeroMatricule != null %} {# modif prix si police #}
                            {% set produitprix = produit.produit.priceFDO %}
                        {% endif %}
                    {% endif %}

                    {% if siFDO == false %}
                        {% set siFDO = true %} {# variable utilisé uniquement pour l'explication des documents à fournir avant de faire un achat #}
                    {% endif %}
                {% endif %}
                
                <tr>
                    <th>
                     {% if produit.produit.category != "Prestation" %}
                    <a href="{{ path('app_produit',{'slug': produit.produit.slug}) }}">
                        <div class="cart_produit border_radius_all_15 box_shadow_all">
                            <img src="{{ (produit.produit.illustration starts with "http") ? '' : '/uploads/'  }}{{ produit.produit.illustration }}" alt="{{ produit.produit.name }}"><br/>
                            {% if produit.produit.isDegressif %} 
                                    <strong style="color: green;">Prix dégressif</strong>
                            {% endif %}
                        </div>
                        </a>
                        {% else %}
                        <div class="cart_produit border_radius_all_15 box_shadow_all">
                            <img src="{{ (produit.produit.illustration starts with "http") ? '' : '/uploads/'  }}{{ produit.produit.illustration }}" alt="{{ produit.produit.name }}"><br/>
                        </div>
                        {% endif %}
                    </th>
                    <td>
                        <h4>{{ produit.produit.name|upper }}</h4>
                        <p>{{produit.produit.subtitle}}</p>
                        {% if produit.produit.category == "Prestation" %}
                            <b>Prestation</b><br/>
                        {% elseif produit.bourseArme %}
                            <b class="mr-2">Quantité(s) : </b>
                            {{ produit.quantity }}
                        {% else %}
                            <b class="mr-2">Quantité(s)</b>
                            <a href="{{ path('decrease_to_cart',{'id' : produit.produit.id}) }}"><i class="fa-solid fa-circle-minus icone"></i>
                            </a>
                            <input type="number" min="0" class="compteurQuantiteCart" class="mx-1" value="{{ produit.quantity }}" data-pid="{{produit.produit.id}}"/>
                            <a href="{{ path('add_to_cart',{'id': produit.produit.id}) }}"><i class="fa-solid fa-circle-plus icone"></i>
                            </a>
                            {% if produit.produit.quantite <= 0 %}
                                <b>Pré-commande</b>
                            {% endif %}
                        {% endif %}

                        <a class="ml-4" href="{{ path('delete_to_cart',{'id': produit.produit.id}) }}"><i class="fa-solid fa-trash-can icone"></i></a><br/><br/>
                    {% if affichePrix == true %}
                        {% if produit.produit.isDegressif and produit.quantity >= 10 %}
                            {# <b>{{ (produitprix / 100)|number_format(2, ',','.') }} €</b> #}
                             {% if produit.produit.isDegressif and produit.quantity >= 10 %} {# GESTION PRIX PRODUIT EN DEGRESSIF #}
                                {% set key = 1 %}
                                {% set degressifPrixCheckStop = false %}
                                {% for val in produit.produit.degressifValues %}
                                    {% if degressifPrixCheckStop == false %}
                                        {% if (produit.produit.degressifValues[key + 1] is defined) == false %}
                                            {% if val <= produit.quantity %}
                                                {% set produitprix = produitprix - (key * 50) %}
                                                {% set degressifPrixCheckStop = true %}
                                            {% endif %}
                                        {% else %}
                                            {% if produit.quantity >= val and produit.quantity < produit.produit.degressifValues[key + 1] %}
                                                {% if val == 10 %} {# si quantité prise à 20 | pour que ça fonctionne j'ai dû mettre la valeur précédente qui est de 10 #}
                                                    {% set produitprix = produitprix - (key * 50) - 20 %} {# valeur key - 20 centimes de remise en plus #}
                                                {% else %}
                                                    {% set produitprix = produitprix - (key * 50) %} {# valeur key - 50 centimes pour affecter un prix degressif #}
                                                {% endif %}
                                                {% set degressifPrixCheckStop = true %}
                                            {% endif %}
                                        
                                            {% if degressifPrixCheckStop == false %}
                                                {% set key = key + 1 %}
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            <h3>{{ ((produitprix * produit.quantity) / 100)|number_format(2, ',','.') }} €</h3><br/>
                        {% else %}
                            {# <b>{{ (produitprix / 100)|number_format(2, ',','.') }} €</b> #}
                            <h3>{{ ((produitprix * produit.quantity) / 100)|number_format(2, ',','.') }} €</h3><br/>
                        {% endif %}
                    {% endif %}
                        
                </td>
                </tr>
                {# {% if produit.produit.isDegressif and produit.quantity >= 10 %}
                    {% set total = total + (produitprix * produit.quantity) - (produit.quantity) * 50 %}
                {% else %} #}
                    {% set total = total + (produitprix * produit.quantity)  %}
                {# {% endif %} #}
            {% endfor %}
            </tbody>
        </table>
        {% if indisponible %}
        <hr>
        <table class="table table_cart">
            <tbody>
                    <p>Certains des produits présents de votre panier ne sont plus disponibles</p><br/>
                    {% for nonAffiche in indisponible %} {# produits qui étaient dans le panier mais sont devenus non affichés #}
                    <tr>
                        <th>
                        {% if nonAffiche.produit.category != "Prestation" %}
                        <a href="{{ path('app_produit',{'slug': nonAffiche.produit.slug}) }}">
                            <div class="cart_produit border_radius_all_15 box_shadow_all">
                                <img src="/uploads/{{ nonAffiche.produit.illustration }}" alt="{{ nonAffiche.produit.name }}"><br/>
                            </div>
                            </a>
                            {% else %}
                            <div class="cart_produit border_radius_all_15 box_shadow_all">
                                <img src="/uploads/{{ nonAffiche.produit.illustration }}" alt="{{ nonAffiche.produit.name }}"><br/>
                            </div>
                            {% endif %}
                        </th>
                        <td>
                            <h4>{{ nonAffiche.produit.name|upper }}</h4>
                            <p>{{ nonAffiche.produit.subtitle }}</p>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        {% if app.user %}
            {% if documentClient %}
                {% if siFDO and documentClient.cartPoliceId == null %}
                    <p class="text-danger font-weight-bold">La CARTE POLICE et matricule sont obligatoire pour acheter les produits classés en FORCES DE L'ORDRE. Il peut y avoir des frais qui seront appliqués en cas d'annulation. La remise n'est pas valable pour les réservistes et retraités</p>
                {% endif %}
                {% if documentClient.cartId %} {# si CNI enregistre #}
                    <p class="text-success">Vous avez au moins un document enregistré : Carte nationale</p>
                {% endif %}
            {% else %}
                {% if siFDO %}
                    <p class="text-danger font-weight-bold">La CARTE POLICE et matricule sont obligatoire pour acheter les produits classés en FORCES DE L'ORDRE. Il peut y avoir des frais qui seront appliqués en cas d'annulation. La remise n'est pas valable pour les réservistes et retraités</p>
                {% endif %}
                <p class="text-danger font-weight-bold">Veuillez déposer vos documents pour continuer la commande. <br/><a href="{{path('app_account_documents')}}">Déposer mes documents</a></p>
            {% endif %}
        {% endif %}
        <hr>
        <div class="text-right mb-5">
            <b>Nombre de produit :</b> {{ cart|length }}  <br/>
            <b>Total de mon panier : </b><b>{{ (total / 100)|number_format(2, ',','.') }} €</b>
            <a href="{{ path('app_order') }}" class="btn btn-success btn-block mt-3 border_radius_all w-50 mx-auto">Valider mon panier</a>
        </div>
        {% else %}
            <hr>
            <p><b>Votre panier est vide</b></p>
        {% endif %}
    {% endblock %}
    {% block js %}
        <script src="{{ asset('assets/js/01da8958ef564a24b0c81d684f32b80.js') }}?v={{version}}"></script>
    {% endblock %}